# FamilySpace/docker-compose.yml
version: "3.8"

services:
  postgres-dev:
    image: postgres:16-alpine
    container_name: familyspace-db-dev
    environment:
      POSTGRES_USER: andrewqa
      POSTGRES_PASSWORD: 05052002
      POSTGRES_DB: familyspace_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata_dev:
